config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "reviews#index"
  resources :reviews, only: [:index, :new, :create, :show] do
    resources :comments, only: [:new, :create]
  end
  resources :styles, only: [:show, :new, :create]
  resources :breweries, only: [:show, :new, :create]
  resources :reviewers, only: [:show, :new, :create]
  resources :users, only: [:edit, :update,]
  resources :guides, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  has_many :reviews
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reviewer
  belongs_to :style
  belongs_to :brewery
  has_many :comments
  is_impressionable counter_cache: true

  mount_uploader :image, ImageUploader
end

app/models/reviewer.rb
class Reviewer < ApplicationRecord
  has_many :reviews
end

app/models/style.rb
class Style < ApplicationRecord
  has_many :reviews
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :comments

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  def show   
    @brewery = Brewery.find(params[:id])
    @reviews = Review.where(brewery_id: @brewery).order("created_at DESC").page(params[:page]).per(8)
  end  

  def new
    @brewery = Brewery.new 
  end

  def create
    @brewery = Brewery.new(brewery_params)
      if @brewery.save
      redirect_to root_path
      end
  end

  private
  def brewery_params
    params.require(:brewery).permit(:brewery_name, :brewery_country, :brewery_city, :image, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
  def new
    @review = Review.find(params[:review_id])
    @comment = Comment.new
 end
 
 
  def create
    comment = Comment.create(comment_params)
    redirect_to "/reviews/#{comment.review.id}" 
  end

  private
  def comment_params
    params.require(:comment).permit(:text, :rate, :beer_spot_name, :beer_spot_city, :beer_spot_url).merge(user_id: current_user.id, review_id: params[:review_id])
  end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  def index 
  end
end

app/controllers/reviewers_controller.rb
class ReviewersController < ApplicationController
  def show    
    @reviewer = Reviewer.find(params[:id]) 
    @reviews = Review.where(reviewer_id: @reviewer).order("created_at DESC").page(params[:page]).per(8)
  end

  def new
    @reviewer = Reviewer.new 
  end

  def create
    @reviewer = Reviewer.new(reviewer_params)
      if @reviewer.save
      redirect_to root_path
      end
  end

  private
  def reviewer_params
    params.require(:reviewer).permit(:company_name, :reviewer_name, :image, :guide_text)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  def index
    @reviews = Review.all.order("created_at DESC").page(params[:page]).per(8)
    @topreview = Review.order(impressions_count: "DESC").first
    @secondreview = Review.order(impressions_count: "DESC").second
    @thirdreview = Review.order(impressions_count: "DESC").third
  end

  def new
    if  current_user.admin == false
        redirect_to root_path
    else
        @review = Review.new 
    end
    
  end

  def create
    @review = Review.new(review_params)
      if @review.save
      redirect_to root_path
      end
  end

  def show
    @review = Review.find(params[:id])
    impressionist(@review, nil, unique: [:session_hash.to_s])
    @comment = Comment.new
    @comments = @review.comments.includes(:user).order("created_at DESC")
  end

  private
  def review_params
    params.require(:review).permit(:beer_name, :image, :text, :rate, :abv, :ibu, :ec_goodbeer, :ec_amazon, :ec_rakuten, :beer_spot_name, :beer_spot_city, :beer_spot_url, :reviewer_id, :style_id, :brewery_id)  
  end

end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  def show
  @style = Style.find(params[:id])
  @reviews = Review.where(style_id: @style).order("created_at DESC").page(params[:page]).per(8)
  end

  def new
    @style = Style.new 
  end

  def create
    @style = Style.new(style_params)
      if @style.save
      redirect_to root_path
      end
  end

  private
  def style_params
    params.require(:style).permit(:beer_style, :text, :image)
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/reviewers_helper.rb
module ReviewersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/breweries/_main-breweries.html.haml
.main
  .main__top
    .main__top__left-box
      %ul.main__top__left-box__guide
        メニュー
        %li.main__top__left-box__guide__start-guide
          = link_to guides_path do
            ✔️麦酒どっとこむとは
        - if user_signed_in?
          %li.main__top__left-box__guide__login
            = link_to edit_user_path(current_user) do
              ✔️ログアウト/編集          
        - else
          %li.main__top__left-box__guide__login
            = link_to "users/sign_in" do
              ✔️ログイン       
      %ul.main__top__left-box__search
        ビールを探す
        %li.main__top__left-box__search__style
          ▼スタイルから探す
          %ul
            %li
              ▼エール  
              %ul
                %li
                  = link_to style_path(1) do
                    IPA 
                %li
                  = link_to style_path(2) do
                    ホワイトエール  
                %li
                  = link_to style_path(3) do
                    ベルジャンエール 
                %li
                  = link_to style_path(4) do
                    セゾン  
                %li
                  = link_to style_path(5) do
                    スタウト 
                %li
                  = link_to style_path(6) do
                    ポーター
                %li
                  = link_to style_path(7) do
                    ストロングエール
                %li
                  = link_to style_path(8) do
                    その他エール                                                                                                                    
            %li               
              ▼ラガー 
              %ul
                %li
                  = link_to style_path(9) do
                    ピルスナー
                %li
                  = link_to style_path(10) do
                    ダークラガー  
                %li
                  = link_to style_path(11) do
                    その他ラガー                
            %li
              ▼その他  
              %ul
                %li
                  = link_to style_path(12) do
                    ランビック
                %li
                  = link_to style_path(13) do
                    サワー  
                %li
                  = link_to style_path(14) do
                    その他                
        %li.main__top__left-box__search__brewery
          ▼ブリュワリーから探す
          %ul
            %li
              ▼日本  
              %ul
                %li
                  = link_to brewery_path(1) do
                    玉村本店 
                %li
                  = link_to brewery_path(2) do
                    伊勢角屋麦酒  
                %li
                  = link_to brewery_path(3) do
                    わかさいも本舗
                %li
                  = link_to brewery_path(4) do
                    Far Yeast Brewing
                %li
                  = link_to brewery_path(5) do
                    箕面ビール
                %li
                  = link_to brewery_path(6) do
                    Y.MARKET
                %li
                  = link_to brewery_path(7) do
                    COEDO                                                            
          %ul
            %li
              ▼海外
              %ul    
                %li
                  = link_to brewery_path(8) do
                    BrewDog 
                %li
                  = link_to brewery_path(9) do
                    Mikkeller
                %li
                  = link_to brewery_path(10) do
                    Thornbridge   
                %li
                  = link_to brewery_path(11) do
                    De Ranke                                                                                             
        %li.main__top__left-box__search__reviewer
          ▼レビュアーから探す     
          %ul
            %li
              = link_to reviewer_path(1) do
                運営者          

    .main__top__right-box
      .main__top__right-box__image-box
        = image_tag @brewery.image, size: "300x245", alt: "Image Comming Soon"
      .main__top__right-box__review-box
        .main__top__right-box__review-box__top3
          .main__top__right-box__review-box__top3__beer-spec
            .main__top__right-box__review-box__top3__beer-spec__brewery-name
              = @brewery.brewery_name
            .main__top__right-box__review-box__top3__beer-spec__brewery-city
              @
              = @brewery.brewery_city
        .main__top__right-box__review-box__bottom
          .main__top__right-box__review-box__bottom__review-summary
            = @brewery.text
  .main__bottom
    
    - @reviews.each do |review|
      .main__bottom__review-box
        .main__bottom__review-box__top
          = link_to "/reviews/#{review.id}" do
            .main__bottomz__review-box__top__beer-image
              = image_tag review.image.url , size: "160x140", alt: "Image Comming Soon"
            .main__bottom__review-box__top__beer-name
              = review.beer_name
        .main__bottom__review-box__bottom
          .main__bottom__review-box__bottom__content
            = link_to "/reviews/#{review.id}" do
              .main__bottom__review-box__bottom__content__reviewer-info
                .main__bottom__review-box__bottom__content__reviewer-info__image
                  = image_tag review.reviewer.image, size: "60x50", alt: "Image Comming Soon"  
                .main__bottom__review-box__bottom__content__reviewer-info__name
                  = review.reviewer.reviewer_name
            .main__bottom__review-box__bottom__content__beer-info
              .main__bottom__review-box__bottom__content__beer-info__brewery
                ブリュワリー名：
                = review.brewery.brewery_name
              .main__bottom__review-box__bottom__content__beer-info__style
                スタイル：
                = review.style.beer_style
          .main__bottom__review-box__bottom__review-summary
            = truncate(review.text, :length => 70)
            = link_to "/reviews/#{review.id}" do
              more
          .main__bottom__review-box__bottom__rate
            %div{:id => "star-rate-#{review.id}"}
              :javascript
                $('#star-rate-#{review.id}').raty({
                  number: 5,
                  size: 36,
                  starOff: "#{asset_path('star-off.png')}",
                  starOn: "#{asset_path('star-on.png')}",
                  starHalf: "#{asset_path('star-half.png')}",
                  half: true,
                  readOnly: true,
                  score: "#{review.rate}",
                  });
    
.paginate
  = paginate(@reviews)

app/views/breweries/new.html.haml
.wrapper
  = render "reviews/header"
  = render "new-main"
  = render "reviews/footer"

app/views/breweries/show.html.haml
.wrapper
  = render "reviews/header"
  = render "main-breweries"
  = render "reviews/footer"

app/views/brewery/_main-breweries.html.haml
.main
  .main__top
    .main__top__left-box
      %ul.main__top__left-box__guide
        メニュー
        %li.main__top__left-box__guide__start-guide
          = link_to "#" do
            ✔️麦酒どっとこむとは
        - if user_signed_in?
          %li.main__top__left-box__guide__login
            = link_to edit_user_path(current_user) do
              ✔️ログアウト/編集          
        - else
          %li.main__top__left-box__guide__login
            = link_to "users/sign_in" do
              ✔️ログイン       
      %ul.main__top__left-box__search
        ビールを探す
        %li.main__top__left-box__search__style
          ▼スタイルから探す
          %ul
            %li
              ▼エール  
              %ul
                %li
                  = link_to style_path(1) do
                    IPA 
                %li
                  = link_to style_path(2) do
                    ホワイトエール  
                %li
                  = link_to style_path(3) do
                    ベルジャンエール 
                %li
                  = link_to style_path(4) do
                    セゾン  
                %li
                  = link_to style_path(5) do
                    スタウト 
                %li
                  = link_to style_path(6) do
                    ポーター
                %li
                  = link_to style_path(7) do
                    ストロングエール
                %li
                  = link_to style_path(8) do
                    その他エール                                                                                                                    
            %li               
              ▼ラガー 
              %ul
                %li
                  = link_to style_path(9) do
                    ピルスナー
                %li
                  = link_to style_path(10) do
                    ダークラガー  
                %li
                  = link_to style_path(11) do
                    その他ラガー                
            %li
              ▼その他  
              %ul
                %li
                  = link_to style_path(12) do
                    ランビック
                %li
                  = link_to style_path(13) do
                    サワー  
                %li
                  = link_to style_path(14) do
                    その他                
        %li.main__top__left-box__search__brewery
          ▼ブリュワリーから探す
          %ul
            %li
              ▼日本  
              %ul
                %li
                  = link_to brewery_path(1) do
                    玉村本店 
                %li
                  = link_to brewery_path(2) do
                    伊勢角屋麦酒  
                %li
                  = link_to brewery_path(3) do
                    わかさいも本舗
                %li
                  = link_to brewery_path(4) do
                    Far Yeast Brewing
                %li
                  = link_to brewery_path(5) do
                    箕面ビール
                %li
                  = link_to brewery_path(6) do
                    Y.MARKET
                %li
                  = link_to brewery_path(7) do
                    COEDO                                                            
          %ul
            %li
              ▼海外
              %ul    
                %li
                  = link_to brewery_path(8) do
                    BrewDog 
                %li
                  = link_to brewery_path(9) do
                    Mikkeller
                %li
                  = link_to brewery_path(10) do
                    Thornbridge   
                %li
                  = link_to brewery_path(11) do
                    De Ranke                                                                                             
        %li.main__top__left-box__search__reviewer
          ▼レビュアーから探す     
          %ul
            %li
              = link_to reviewer_path(1) do
                運営者          

    .main__top__right-box
      .main__top__right-box__image-box
        = image_tag @brewery.image, size: "300x245", alt: "Image Comming Soon"
      .main__top__right-box__review-box
        .main__top__right-box__review-box__top3
          .main__top__right-box__review-box__top3__beer-spec
            .main__top__right-box__review-box__top3__beer-spec__brewery-name
              = @brewery.brewery_name
            .main__top__right-box__review-box__top3__beer-spec__brewery-city
              @
              = @brewery.brewery_city
        .main__top__right-box__review-box__bottom
          .main__top__right-box__review-box__bottom__review-summary
            = @brewery.text
  .main__bottom
    
    - @reviews.each do |review|
      .main__bottom__review-box
        .main__bottom__review-box__top
          = link_to "/reviews/#{review.id}" do
            .main__bottomz__review-box__top__beer-image
              = image_tag review.image.url , size: "160x140", alt: "Image Comming Soon"
            .main__bottom__review-box__top__beer-name
              = review.beer_name
        .main__bottom__review-box__bottom
          .main__bottom__review-box__bottom__content
            = link_to "/reviews/#{review.id}" do
              .main__bottom__review-box__bottom__content__reviewer-info
                .main__bottom__review-box__bottom__content__reviewer-info__image
                  = image_tag review.reviewer.image, size: "60x50", alt: "Image Comming Soon"  
                .main__bottom__review-box__bottom__content__reviewer-info__name
                  = review.reviewer.reviewer_name
            .main__bottom__review-box__bottom__content__beer-info
              .main__bottom__review-box__bottom__content__beer-info__brewery
                ブリュワリー名：
                = review.brewery.brewery_name
              .main__bottom__review-box__bottom__content__beer-info__style
                スタイル：
                = review.style.beer_style
          .main__bottom__review-box__bottom__review-summary
            = truncate(review.text, :length => 70)
            = link_to "/reviews/#{review.id}" do
              more
          .main__bottom__review-box__bottom__rate
            %div{:id => "star-rate-#{review.id}"}
              :javascript
                $('#star-rate-#{review.id}').raty({
                  number: 5,
                  size: 36,
                  starOff: "#{asset_path('star-off.png')}",
                  starOn: "#{asset_path('star-on.png')}",
                  starHalf: "#{asset_path('star-half.png')}",
                  half: true,
                  readOnly: true,
                  score: "#{review.rate}",
                  });
    
.paginate
  = paginate(@reviews)

app/views/reviewers/_main-reviewer.html.haml
.main
  .main__top
    .main__top__left-box
      %ul.main__top__left-box__guide
        メニュー
        %li.main__top__left-box__guide__start-guide
          = link_to guides_path do
            ✔️麦酒どっとこむとは
        - if user_signed_in?
          %li.main__top__left-box__guide__login
            = link_to edit_user_path(current_user) do
              ✔️ログアウト/編集          
        - else
          %li.main__top__left-box__guide__login
            = link_to "users/sign_in" do
              ✔️ログイン       
      %ul.main__top__left-box__search
        ビールを探す
        %li.main__top__left-box__search__style
          ▼スタイルから探す
          %ul
            %li
              ▼エール  
              %ul
                %li
                  = link_to style_path(1) do
                    IPA 
                %li
                  = link_to style_path(2) do
                    ホワイトエール  
                %li
                  = link_to style_path(3) do
                    ベルジャンエール 
                %li
                  = link_to style_path(4) do
                    セゾン  
                %li
                  = link_to style_path(5) do
                    スタウト 
                %li
                  = link_to style_path(6) do
                    ポーター
                %li
                  = link_to style_path(7) do
                    ストロングエール
                %li
                  = link_to style_path(8) do
                    その他エール                                                                                                                    
            %li               
              ▼ラガー 
              %ul
                %li
                  = link_to style_path(9) do
                    ピルスナー
                %li
                  = link_to style_path(10) do
                    ダークラガー  
                %li
                  = link_to style_path(11) do
                    その他ラガー                
            %li
              ▼その他  
              %ul
                %li
                  = link_to style_path(12) do
                    ランビック
                %li
                  = link_to style_path(13) do
                    サワー  
                %li
                  = link_to style_path(14) do
                    その他                
        %li.main__top__left-box__search__brewery
          ▼ブリュワリーから探す
          %ul
            %li
              ▼日本  
              %ul
                %li
                  = link_to brewery_path(1) do
                    玉村本店 
                %li
                  = link_to brewery_path(2) do
                    伊勢角屋麦酒  
                %li
                  = link_to brewery_path(3) do
                    わかさいも本舗
                %li
                  = link_to brewery_path(4) do
                    Far Yeast Brewing
                %li
                  = link_to brewery_path(5) do
                    箕面ビール
                %li
                  = link_to brewery_path(6) do
                    Y.MARKET
                %li
                  = link_to brewery_path(7) do
                    COEDO                                                            
          %ul
            %li
              ▼海外
              %ul    
                %li
                  = link_to brewery_path(8) do
                    BrewDog 
                %li
                  = link_to brewery_path(9) do
                    Mikkeller
                %li
                  = link_to brewery_path(10) do
                    Thornbridge   
                %li
                  = link_to brewery_path(11) do
                    De Ranke                                                                                             
        %li.main__top__left-box__search__reviewer
          ▼レビュアーから探す     
          %ul
            %li
              = link_to reviewer_path(1) do
                運営者

    .main__top__right-box
      .main__top__right-box__image-box
        = image_tag @reviewer.image, size: "280x240", alt: "Image Comming Soon"
      .main__top__right-box__review-box
        .main__top__right-box__review-box__top4
          .main__top__right-box__review-box__top4__beer-spec
            .main__top__right-box__review-box__top4__beer-spec__reviewer-name
              = @reviewer.reviewer_name
        .main__top__right-box__review-box__bottom
          .main__top__right-box__review-box__bottom__review-summary
            = @reviewer.guide_text
  .main__bottom
    
    - @reviews.each do |review|
      .main__bottom__review-box
        .main__bottom__review-box__top
          = link_to "/reviews/#{review.id}" do
            .main__bottomz__review-box__top__beer-image
              = image_tag review.image.url , size: "160x140", alt: "Image Comming Soon"
            .main__bottom__review-box__top__beer-name
              = review.beer_name
        .main__bottom__review-box__bottom
          .main__bottom__review-box__bottom__content
            = link_to "/reviews/#{review.id}" do
              .main__bottom__review-box__bottom__content__reviewer-info
                .main__bottom__review-box__bottom__content__reviewer-info__image
                  = image_tag review.reviewer.image, size: "60x50", alt: "Image Comming Soon"  
                .main__bottom__review-box__bottom__content__reviewer-info__name
                  = review.reviewer.reviewer_name
            .main__bottom__review-box__bottom__content__beer-info
              .main__bottom__review-box__bottom__content__beer-info__brewery
                ブリュワリー名：
                = review.brewery.brewery_name
              .main__bottom__review-box__bottom__content__beer-info__style
                スタイル：
                = review.style.beer_style
          .main__bottom__review-box__bottom__review-summary
            = truncate(review.text, :length => 70)
            = link_to "/reviews/#{review.id}" do
              more
          .main__bottom__review-box__bottom__rate
            ★★★★★
    
.paginate
  = paginate(@reviews)

app/views/styles/_main-styles.html.haml
.main
  .main__top
    .main__top__left-box
      %ul.main__top__left-box__guide
        メニュー
        %li.main__top__left-box__guide__start-guide
          = link_to guides_path do
            ✔️麦酒どっとこむとは
        - if user_signed_in?
          %li.main__top__left-box__guide__login
            = link_to edit_user_path(current_user) do
              ✔️ログアウト/編集          
        - else
          %li.main__top__left-box__guide__login
            = link_to "users/sign_in" do
              ✔️ログイン       
      %ul.main__top__left-box__search
        ビールを探す
        %li.main__top__left-box__search__style
          ▼スタイルから探す
          %ul
            %li
              ▼エール  
              %ul
                %li
                  = link_to style_path(1) do
                    IPA 
                %li
                  = link_to style_path(2) do
                    ホワイトエール  
                %li
                  = link_to style_path(3) do
                    ベルジャンエール 
                %li
                  = link_to style_path(4) do
                    セゾン  
                %li
                  = link_to style_path(5) do
                    スタウト 
                %li
                  = link_to style_path(6) do
                    ポーター
                %li
                  = link_to style_path(7) do
                    ストロングエール
                %li
                  = link_to style_path(8) do
                    その他エール                                                                                                                    
            %li               
              ▼ラガー 
              %ul
                %li
                  = link_to style_path(9) do
                    ピルスナー
                %li
                  = link_to style_path(10) do
                    ダークラガー  
                %li
                  = link_to style_path(11) do
                    その他ラガー                
            %li
              ▼その他  
              %ul
                %li
                  = link_to style_path(12) do
                    ランビック
                %li
                  = link_to style_path(13) do
                    サワー  
                %li
                  = link_to style_path(14) do
                    その他                
        %li.main__top__left-box__search__brewery
          ▼ブリュワリーから探す
          %ul
            %li
              ▼日本  
              %ul
                %li
                  = link_to brewery_path(1) do
                    玉村本店 
                %li
                  = link_to brewery_path(2) do
                    伊勢角屋麦酒  
                %li
                  = link_to brewery_path(3) do
                    わかさいも本舗
                %li
                  = link_to brewery_path(4) do
                    Far Yeast Brewing
                %li
                  = link_to brewery_path(5) do
                    箕面ビール
                %li
                  = link_to brewery_path(6) do
                    Y.MARKET
                %li
                  = link_to brewery_path(7) do
                    COEDO                                                            
          %ul
            %li
              ▼海外
              %ul    
                %li
                  = link_to brewery_path(8) do
                    BrewDog 
                %li
                  = link_to brewery_path(9) do
                    Mikkeller
                %li
                  = link_to brewery_path(10) do
                    Thornbridge   
                %li
                  = link_to brewery_path(11) do
                    De Ranke                                                                                             
        %li.main__top__left-box__search__reviewer
          ▼レビュアーから探す     
          %ul
            %li
              = link_to reviewer_path(1) do
                運営者   

    .main__top__right-box
      .main__top__right-box__image-box
        = image_tag @style.image, size: "280x240", alt: "Image Comming Soon"
      .main__top__right-box__review-box
        .main__top__right-box__review-box__top2
          .main__top__right-box__review-box__top2__beer-spec
            .main__top__right-box__review-box__top2__beer-spec__style-name
              ”
              = @style.beer_style
              ”とは
        .main__top__right-box__review-box__bottom
          .main__top__right-box__review-box__bottom__review-summary
            = @style.text
  .main__bottom
    
    - @reviews.each do |review|
      .main__bottom__review-box
        .main__bottom__review-box__top
          = link_to "/reviews/#{review.id}" do
            .main__bottomz__review-box__top__beer-image
              = image_tag review.image.url , size: "160x140", alt: "Image Comming Soon"
            .main__bottom__review-box__top__beer-name
              = review.beer_name
        .main__bottom__review-box__bottom
          .main__bottom__review-box__bottom__content
            = link_to "/reviews/#{review.id}" do
              .main__bottom__review-box__bottom__content__reviewer-info
                .main__bottom__review-box__bottom__content__reviewer-info__image
                  = image_tag review.reviewer.image, size: "60x50", alt: "Image Comming Soon"  
                .main__bottom__review-box__bottom__content__reviewer-info__name
                  = review.reviewer.reviewer_name
            .main__bottom__review-box__bottom__content__beer-info
              .main__bottom__review-box__bottom__content__beer-info__brewery
                ブリュワリー名：
                = review.brewery.brewery_name
              .main__bottom__review-box__bottom__content__beer-info__style
                スタイル：
                = review.style.beer_style
          .main__bottom__review-box__bottom__review-summary
            = truncate(review.text, :length => 70)
            = link_to "/reviews/#{review.id}" do
              more
          .main__bottom__review-box__bottom__rate
            %div{:id => "star-rate-#{review.id}"}
              :javascript
                $('#star-rate-#{review.id}').raty({
                  number: 5,
                  size: 36,
                  starOff: "#{asset_path('star-off.png')}",
                  starOn: "#{asset_path('star-on.png')}",
                  starHalf: "#{asset_path('star-half.png')}",
                  half: true,
                  readOnly: true,
                  score: "#{review.rate}",
                  });
    
.paginate
  = paginate(@reviews)
    


    